---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-strawslabs
  namespace: networking
spec:
  encryptedData:
    api-token: AgAhPWdxN3DleqsdNeKQd+YX3gkllwvyM5IR50OHXlfJd6pR2zaEmZRG+OELIeQ5yDfWRG1aqbJvPqQMfxTGYyVhStgYa1cI3Yk640gFRKlUDCBPRYB2n+yiQwKUtm0jhXgMSspNl0vWbt+yEpWkrLkDW5o2b0tdafO4u1a36dOIuI/1qCKBp/apX/Mcq6UpwcpFo3dSo7xap7f7ltNoZd5KgXtjoLMI7s45HjK7tCrHVt818SWdeEq8gkKCF9NvwwutVBOxrppWHPE3JO/kgpWjmcPP1quSDIBlHj2psYNBAPHrDYq3hszbF8+nuh/0fkgxi8U5JXF+B7TosqUDQZe/kXnDufWes0ICRjOsNU7V85SrUz2pkGyJoLaZInUOFFKLkJXGw4RNFseaKAg19LMLTlSuj9LSsLVnxKaIEbGFvwVjBaKr8teCgqoM6SbamBo5kxIl+j7Aiei7hDBRXk0f/35YdoyibWck9lWg7N66KJg7x+GK5OlMrR4gNvc0v9TNqY6krwpRIdDk6OXjxDzed15IUkBIRb82w19W0xncBVebTbivVXDDZDzHUkb7saXcXaofgCxjF7t8M21WJ/VBjWzCR9n9qmFJx0bBI0YNiMIrGap8V1u81yKM6HwenhZQAJFNwYxqZJmkqsIUIknETjmszsuCtDVVcrc3AQByW7lgi08cpsm+g0N9Voyf/vVd5XfIxspm97B0gC3U5ft06t15KBvwC1YCc96pSkpPqc3eyH2B2xWvjeoesSuywI45fdsl7g==
  template:
    metadata:
      name: cloudflare-dns-strawslabs
      namespace: networking
