---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-strawslabs
  namespace: networking
spec:
  encryptedData:
    api-token: AgAjgQU8xhc20s2ThAVC5aA+ERW3Qf7MOiwqT1ECy0HRWCdbH1qE83egbzaIIzFpIxUGMLc6nVToft8I8KEsd4r7JNX0lwmGrADJPPHO7sjkMhoNWw2gnsfMAPWPiZufgjdeFlfQjN+4TMCVjleL5hTzha6qld22XtWTGP1uHU4s2iXnIPagEwAftbLUVNzEQgEfLw/IEaCyRn7rI46CLi6ZNboLEAxJ0dGCssCbroWupA5k9Rz69Rbx7g6ChYnPHarunRCMJ9cPaNUDyRMNfDUhwXuSKhyQvmPguB/hzbh8M72dCSQ/VAyGqx7PGMR+TJ1Ih/rmasSyzNNpV9shL/ztFveKztUxuctjehjURVgSaN4oWSor9tKLB+RQoRdKO6vbU7x23D7p+t/MqfRm24aJkzR67n+pxuz58aoAJs36Hr6GJRuOAtjlYgPMtPttG+ay+GA5e03OoAIWe+cPB6NnLh1l157rH9b+6i60mZJxandl752iaSLFuuAaHprJm+yovNntdmbcjrFzuQqNTobOoT80ETicpFTIhiC6IIzMf6/Ebci1YKQ60XRswoP161z5cqJB6FDWu5PdJXgP4apgkEHOd2eBd7Etktq0zhp8wQa3Mvg87RIafVQyytod4e7Kv+B3ScEYmCzZcvDLkyYVwyeA2NPgGciyPiInQFLbaoE/5W+uNTrxZyOWrRhtorvRFWvMX3U7M4oyLs8AiQyW4b+KMHC+SRodQw0hpj8PBPD9M02AcDl88mUiJPywdmzUqDUc+Q==
  template:
    metadata:
      name: cloudflare-dns-strawslabs
      namespace: networking
