---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-strawslabs
  namespace: networking
spec:
  encryptedData:
    api-token: AgBnIqVqJBxtcC78UUd3diy750iOwJWwZRar4Ap0jIpnFOe52LsFuoFjVXzXF7lDCdbRvLc9ySsXdJJBwWSxPbubrzPZ/dYvTkpNIvkchX6ZFN9x2dDrWW6c7VeLkbwqmq973VOip2y9ZJ8ZZFfDER+TlY7FEm8Fy0a+AIlXTeqGb085bhrRv079FVVRTL6xb1sohx+KNnDrOSwphn9YAoAsGN67MCc9Uxw2jmuLi/6kl/9X+yLFqRuh5xZuf2jIPRI5bur4YoqNTks6eLls9iGQ05Wc1pOowZcw6JypHOdrl+vo4KufmIOLbmfBJxDynawm74A/g3S6qrCOU7D3Lio8vmcIyvhRnNowMrC2YmwFKOmOuk+JPjgGUIOOtL878ufwOSRK1FAW2DUJ2UAG9TV3tdMzUBShgTRig7b+3M5wmxQFnGS1VP55Cwe09eahYWPDn/S9KuzA4ngPT4sHGGnF15KqX7NuY2pxGCnlrOquNP+osoKyzktEYILovMGmTjfDIZkdLX4SCehBLDD+Y8oV4rsNMf/cPjnCmydD3qLzfg7CeaNj1ZZ+fu+foEi+HsoMh5AtfIx0hbUCEC7S5w+fZxV3dZZJQVVmmx7XLn+UDEmJnlrvjFHzxVZCsJet+lu7I8xzvHCcFSkZl039uQOKcE0ZVo4lEaZZknYBGJUoY0QN6/5WTA55l5l7jAalhSoeRY+ftFAEWGaUTprTm0n8vnwl1unuPRN2poDnn6qaUPUB/2Fw5Cd9QLADMl6L9hw03KZ3ng==
  template:
    metadata:
      name: cloudflare-dns-strawslabs
      namespace: networking
