# tasks/system.yml
---
- name: Set system timezone
  community.general.timezone:
    name: "{{ user_timezone }}"
  tags: [base, timezone]

- name: Enable NTP (Timesync)
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true
  notify: Restart systemd-timesyncd
  tags: [base, time]

- name: Set hostname to inventory name
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags: [base, network]

- name: Generate system locales
  community.general.locale_gen:
    name: "{{ user_locale }}"
    state: present
  tags: [base, locale]

- name: Increase fs.inotify.max_user_instances (Fix "too many open files")
  ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: "8192"
    state: present
    reload: true
  tags: [base, system, performance]

- name: Increase fs.inotify.max_user_watches (Fix "too many open files")
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present
    reload: true
  tags: [base, system, performance]
