apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: couchdb-tls
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: couchdb-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "couchdb.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"