apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/sealed-secrets/base

components:
  - ../../../apps/infrastructure/sealed-secrets/components/minimal
  - ../../../apps/infrastructure/sealed-secrets/components/resource-limits
