apiVersion: velero.io/v1
kind: Restore
metadata:
  name: immich-restore
  namespace: backup
spec:
  backupName: BACKUP_NAME # <-- REPLACE with actual backup name
  includedNamespaces:
    - personal
  includedResources:
    - persistentvolumeclaims
    - persistentvolumes
    - pods
  namespaceMapping:
    personal: restore
  existingResourcePolicy: none
  restorePVs: true
