apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-immich
  namespace: backup
spec:
  schedule: "0 3 * * *" # 03:00 UTC daily, 1h after immich's own DB dump (02:00 UTC)
  template:
    includedNamespaces:
      - personal
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: immich
    storageLocation: aws
    defaultVolumesToFsBackup: true
    ttl: 336h0m0s # 14 daily copies (2 weeks)
