apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: networking
  annotations:
    link.argocd.argoproj.io/external-link: "https://traefik.placeholder.local/dashboard/"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.placeholder.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-dashboard-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-cert
  namespace: networking
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: traefik-dashboard-cert
  dnsNames:
    - traefik.placeholder.local
  commonName: traefik.placeholder.local
