apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

helmCharts:
  - name: couchdb
    repo: https://apache.github.io/couchdb-helm
    version: 4.6.3
    releaseName: couchdb
    namespace: storage
    valuesFile: values.yaml
