---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-aws-creds
  namespace: backup
spec:
  encryptedData:
    cloud: AgARH8yudVMUonj/nT13pkGk8YJEYrJlBudYxWI5tchv8x+75k3qMyqp3pcGONV1EOWOd/kDN8ssVwrurASlLGRwYBr9U5anJjhL5rIIU0L9MEBrOrqBH4X/os82DYQyW86FHOO2Con5xYpU1M72yvIM3VN8WMlnYAM4VtDCLd8aieFagu7GLExTMQlzIOCovnIXKYFvUQDUMmvOCH9N6gSwx3dGQqd1d0UDoth27YIcW687duDShz8xQ4xeizPjLioEn32hiWbaO2s7UZmhV25UWZx82ECeNSwt1w8mJ3ltpuzAzhZut3k2f0nvY8TBsh9UZc5U5MOibyPphTwrn8XLTXMTBSDNvUxeGbBvC4+lYo9UCd5A3D7S30NaJOX9NTSqv1S6C43Jh6F3OB1IOW5BfO+V1HcA8EGxl9BjY1mVsHVC/mr61SY0obO/AwbITByyhlzU+vSbYfu/F050j3kN7RvXVSftx8wwagUSysXCLcEpfG7gAQK4b1kWNNV0MRtrKUaL0fcYDKaxLEhNTYzKJPVcGehqJWu6er3Ol+jXtW4bjRROyTE+Xq9Tp43k6KgnF5VAUgf6VKEf/WcQh7+k7ss1NCRknGJYC0Ju+YkUTPWQi6F1v3vGm+YpSPOZKyDwgFQcAYkbG4Maah7t66SLSYLgmFoz3E35CngZDJqNCoxeYF+eMXR9GtTy4aLIbYYX7vvcBKjuHHaOy+252osAQZPaNsxWdH51bhR4b0FaoxtJ4RP5380ghSAJtwEQb+zVhJFhzJFQHYTaaDIDWfsWCV613Tkfcs+JJ/Lem+NUYAkMbUGbZcO79tuiWSLAw0mFCF6gm1CRCY0UJKQkjg+yOuTdvg==
  template:
    metadata:
      creationTimestamp: null
      name: velero-aws-creds
      namespace: backup
