apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: sre-operations
spec:
  title: "SRE / Operations"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: portal
spec:
  title: "Portal"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: executive
spec:
  title: "Executive"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: developer
spec:
  title: "Developer"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: dba
spec:
  title: "DBA"
