apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: hyperion-grafana:grafana.integreatly.org/GrafanaFolder:monitoring/sre-operations
  name: sre-operations
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: hyperion
  title: "SRE / Operations"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: hyperion-grafana:grafana.integreatly.org/GrafanaFolder:monitoring/portal
  name: portal
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: hyperion
  title: "Portal"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: hyperion-grafana:grafana.integreatly.org/GrafanaFolder:monitoring/executive
  name: executive
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: hyperion
  title: "Executive"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: hyperion-grafana:grafana.integreatly.org/GrafanaFolder:monitoring/developer
  name: developer
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: hyperion
  title: "Developer"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: hyperion-grafana:grafana.integreatly.org/GrafanaFolder:monitoring/dba
  name: dba
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: hyperion
  title: "DBA"
