apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: obsidian-cert-strawslabs
  namespace: personal
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: obsidian-cert-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "obsidian-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"