authentik:
  secret_key: "K2w4Yjd2em0rOG5mZzVlMnc5Z3J5cTdxMmR1YTN4ZmI1aTZvOGwKbjk5YzEycjM0dDV5NnU3aThvOQ=="
  error_reporting:
    enabled: true
  postgresql:
    password: "ThisIsNotASecurePassword"

  envFrom:
    - secretRef:
        name: authentik

server:
  envFrom:
    - secretRef:
        name: authentik
  ingress:
    enabled: true
    hosts:
      - authentik.domain.tld

  # Tune probes to avoid initial 502 errors during Gunicorn startup
  startupProbe:
    initialDelaySeconds: 10
    failureThreshold: 30
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 10
    failureThreshold: 5

worker:
  envFrom:
    - secretRef:
        name: authentik

postgresql:
  enabled: true
  auth:
    password: "ThisIsNotASecurePassword"
