apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/services/podinfo/overlays/dev

namespace: podinfo

components:
  - ../../../apps/services/podinfo/components/ingress
  - ../../../apps/services/podinfo/components/log-level
# - ../../../apps/services/podinfo/components/maintenance
