storage_setup_storage_mounts: >-
  {{ storage_mounts | default([
    { 'device': '/dev/sdb', 'path': '/data/storage', 'fstype': 'ext4' },
    { 'device': '/dev/sdc', 'path': '/data/backups', 'fstype': 'xfs' }
  ]) }}
