apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-s3
  namespace: backup
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: velero-storage-secret-store
  target:
    name: velero-s3
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        - secretKey: aws_access_key_id
          template:
            let:
              accessKey: "{{ .Values.access_key }}"
            toObject:
              aws_access_key_id: "{{ .accessKey }}"
        - secretKey: aws_secret_access_key
          template:
            let:
              secretKey: "{{ .Values.secret_key }}"
            toObject:
              aws_secret_access_key: "{{ .secretKey }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: access_key
    - secretKey: secret_key
      remoteRef:
        key: secret_key
