apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian
  namespace: personal
spec:
  template:
    spec:
      hostAliases:
      - ip: "192.168.0.240"
        hostnames:
        - "couchdb.hyperion.aritrosinha.dpdns.org"
        - "obsidian.hyperion.aritrosinha.dpdns.org"
