apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-master-strawslabs
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-master-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "seaweedfs-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-filer-strawslabs
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-filer-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "filer.seaweedfs-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-s3-strawslabs
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-s3-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "s3.seaweedfs-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-admin-strawslabs
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-admin-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "admin.seaweedfs-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-volume-strawslabs
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-volume-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "volume.seaweedfs-hyperion.strawslabs.com"
    - "*.volume.seaweedfs-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
