apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../certificates/wildcard-ruth-staging
  - ../../secrets/cloudflare-dns-aritrosinha

resources:
  - ../../issuers/letsencrypt-staging-aritrosinha
