ingress:
  enabled: false

containerPorts:
  - name: "http"
    port: 3923
    protocol: "TCP"

configMap:
  enabled: true
  name: copyparty-config
  data:
    config.conf: |-
      [global]
        p: 3923
        xff-src: lan
        http-only

      [accounts]
        admin: d52c8f613a6dfcae21691cb1

      [/]
        .
        accs:
          rwda: admin

volumeConfig:
  userData:
    volumeMount:
      name: "user-data"
      mountPath: "/w"
    volume:
      name: "user-data"
      emptyDir: null
      nfs:
        server: "192.168.0.2"
        path: "/WD4TB/shared/v1"
  appData:
    persistence:
      enabled: true
      pvcName: "app-data"
      accessModes:
        - "ReadWriteOnce"
      size: "1Gi"
      storageClass: "longhorn"
  copypartyConfig:
    volumeMount:
      name: "copyparty-config"
      mountPath: "/cfg"
    volume:
      name: "copyparty-config"
      secret: null
      configMap:
        name: "copyparty-config"

app:
  args: []

resources:
  limits:
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "128Mi"
