apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: storage
spec:
  encryptedData:
    password: AgBRyiz+C6fD6/k9N1hQnwMQQ1eIwJ2px+EUIL4rMwa5btbuAfN3VbRdCgSI/8ilc37EJgeoyj7qYKLI1FBRqDoQ1T/3oqFh14xWolUwdMOpyNWvpT8meqTS8k0MGJElC3szahVCgKPILZ1Io+tzl6m822e0KE+kcRn0HLdCiuxL7pG1e5zdXiVN1QgwXDcYddiH8jCeRNC0Jsm+9kH52eYvPmAjQSYdKECaaO5bT04xfI/uetp+ius63+EtkoCYOzlq3mTudLpKSQPTemXsQXd2iDtYStcQir3jZOWTIXfj52bmWw2gABYaHPU9dflukLAR2Aq8RevaI2sqg6lP8cOB95S9LVbw7IeB4xMWQFnsCxjW/FW35b/VzglaLZbwAMYpPuIv170JltJAVXSFVkjLHTXiD2p6KKcrUClGzUbhjG8xSTWaneKLZGSqCqteg9LUzAhDCKfQ4bN0v/0Ir3Jtse5DRaG2mQKgH3q1ZyVjqKAGkCm9i7OHUMdtH3qjP95TT8DZm+ED2zQ8lhWFUtedktbud5M2u6pV3a75mWDQTHd86ZOTGEgKG52rIPbxhNFuRxrpP+yqf6oKxIWgFbQkl9WnWEIvV2KAXrQyXN3OiwpPCk1zc/nZp0gaSjHtigx2UbZ8843uG5YbVKXB5N7/KdZqKukRWEUry5mxhJ/yM23DTtm/1jU1mZ4pn4cJYFLR+zlDgYiD7rBHpfz96/3QfoWI/6nFdKLV6mfD3ntk
  template:
    metadata:
      name: redis-secret
      namespace: storage
