apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  elysia.override: |
    rewrite name exact authentik.elysia.example.com traefik.networking.svc.cluster.local
