apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-oauth-immich
  namespace: security
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: personal-bridge-store
    kind: ClusterSecretStore
  target:
    name: authentik-oauth-immich
    creationPolicy: Owner
  data:
    - secretKey: IMMICH_OAUTH_CLIENT_ID
      remoteRef:
        key: authentik-oauth-immich
        property: IMMICH_OAUTH_CLIENT_ID
    - secretKey: IMMICH_OAUTH_CLIENT_SECRET
      remoteRef:
        key: authentik-oauth-immich
        property: IMMICH_OAUTH_CLIENT_SECRET
