apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: authentik-immich-blueprint
    files:
      - configs/immich-oauth-provider.yaml
    options:
      disableNameSuffixHash: true

resources:
  - sealed-oauth-immich.yaml
