apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: authentik-immich-blueprint
    files:
      - configs/immich-oauth-provider.yaml
    options:
      disableNameSuffixHash: true

resources:
  - sealed-oauth-immich.yaml

patches:
  - path: patch-blueprint-volume.yaml
    target:
      kind: Deployment
      name: authentik-server
  - path: patch-blueprint-volume-worker.yaml
    target:
      kind: Deployment
      name: authentik-worker
