apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
spec:
  template:
    spec:
      volumes:
        - name: blueprints-immich-oauth
          configMap:
            name: authentik-immich-blueprint
      containers:
        - name: authentik
          volumeMounts:
            - name: blueprints-immich-oauth
              mountPath: "/blueprints/mounted/oauth-immich"
