- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: blueprints-immich-oauth
    configMap:
      name: authentik-immich-blueprint
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: blueprints-immich-oauth
    mountPath: "/blueprints/mounted/oauth-immich"
