apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-test

helmCharts:
  - name: seaweedfs
    repo: https://seaweedfs.github.io/seaweedfs/helm
    version: 4.39.0
    releaseName: seaweedtest
    namespace: storage-test
