master:
  replicas: 3
  electionTimeout: "10s"
  heartbeatInterval: "300ms"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  data:
    type: "persistentVolumeClaim"
    size: "1Gi"
  logs:
    type: "persistentVolumeClaim"
    size: "1Gi"
  affinity: ""
  nodeSelector: {}

volume:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  extraArgs:
    - "-publicUrl=${POD_NAME}.volume.seaweedtest.hyperion.aritrosinha.dpdns.org"
  dataDirs:
    - name: data
      type: "persistentVolumeClaim"
      size: "10Gi"
  idx:
    type: "persistentVolumeClaim"
    size: "1Gi"
  logs:
    type: "persistentVolumeClaim"
    size: "1Gi"
  affinity: ""
  nodeSelector: {}

filer:
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  data:
    type: "persistentVolumeClaim"
    size: "2Gi"
  logs:
    type: "persistentVolumeClaim"
    size: "1Gi"
  affinity: ""
  nodeSelector: {}

admin:
  enabled: true
  port: 23646
  grpcPort: 33646
  existingSecret: "seaweedtest-admin-creds"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  data:
    type: "persistentVolumeClaim"
    size: "2Gi"
  logs:
    type: "persistentVolumeClaim"
    size: "2Gi"
  affinity: ""
  nodeSelector: {}

s3:
  enabled: true
  replicas: 2
  port: 8333
  metricsPort: 9327
  enableAuth: false
  bindAddress: "0.0.0.0"
  domainName: ""
  terminationGracePeriodSeconds: 60
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  logs:
    type: "emptyDir"
  affinity: ""
  nodeSelector: {}

worker:
  enabled: true
  replicas: 1
  metricsPort: 9327
  jobType: "all"
  maxDetect: 1
  maxExecute: 4
  workingDir: "/tmp/seaweedfs-worker"
  terminationGracePeriodSeconds: 60
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  data:
    type: "emptyDir"
  logs:
    type: "emptyDir"
  affinity: ""
  nodeSelector: {}

