apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/traefik/base

components:
  - ../../../apps/infrastructure/traefik/components/minimal
  - ../../../apps/infrastructure/traefik/components/resource-limits
  - ../../../apps/infrastructure/traefik/components/certificate
  # - ../../../apps/infrastructure/traefik/components/maintenance
  - components/dashboard
