apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb-couchdb
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: database-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
