apiVersion: velero.io/v1
kind: Restore
metadata:
  name: security-restore
  namespace: backup
spec:
  backupName: BACKUP_NAME # <-- REPLACE with actual backup name
  includedNamespaces:
    - security
  namespaceMapping:
    security: restore
  existingResourcePolicy: none
  restorePVs: true
