---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obsidian-credentials
  namespace: personal
spec:
  encryptedData:
    password: AgCGCWdJ6OHVDXLiubHVbDH8S/HdFdtlxcz+xfl5LfzooGBA7Vi8/UHJ4jhfsLRq0uEVNRWs5yPa0MAFNbg4iwGVfJAr5ZznizyNO4NGzRMfh4rpaqp+q//oOZz2Rap5h9BYkUAbZfiWSRoez1bZR7cWirko2yLmdEFKX3zjsP3qBx7Uaz2uxwc3xyvt+HV5M/BIYwT4DrL8f0uQPjJKUkecIZqncUecB7W4TVW/JoXRlqO77ZcEM9MSXXOHq0nTK0yGzIQl0qJJzqhkPNF9QkYTb5IPrPRIF9QIzdjlnNPIV5C26i7tCyRBjiKfS/pmooutz8yTp82shb3xTptnqma5GKvKi7m8kCZIitI0oLXsk5RiUmKZSNVUDXRJlANJAN0GOe3H0V3SwD3TRlkeyK0roQLXHabB5iUnuUwsR876KGXZdwkiXaG+fw/cA7YZkNfXcwKG5HnUAHpESKr4NVIK4nN4PtamLVD7bV3RxrpaJonMEUsbq4pWVhl+lsU9nV0nHKnwC4HccGw5FhLb5MmBDkgvjUJdoo/YvPSmayy4g1aIPGNKA0oZlw7r6a9qhXfZjZu/+bNfVT6WKFEQpWjwmOJqwOTrBEm8CGqxsp3EdocdBQlxbzsJwGqSxfdGnB+o9rS9g9L7DB0bf2hepMNoGXRoDmhPRCjPu99Q5BX+JNK5s/BxUtIyANjVjwoTHh1HRdhV/U6OtGirFygoiORn
    username: AgAaDa7JU6Z3pWjVJ10A0cJ80xQrvzjF4XmRnybybBL7o07ZPutp+Hb61Xxvn4A27rRALzB9wVtnwlE6lE6EYvUNErb7FA2iBE2IQ2Xkrt6IJJNzkaiy9b6H4ChjgJ4sZPnZbb8B+bZ1B5TW5DmR7QvHhDKZtC59n8Zqrogch7BNmsMCNMTEpZUaIqfe8emes+lIxB8GpGvbegyjnCCVmZmCoG4dktLfHlzTeUboX5yAY/xV/5wrHgBIIR6c2R+Xc+08bv+8V/G9FDHNdEDeA7k7sPezuKWe1/ZPz1y8JsoZDYaqtxxASNd5TLN0rxruAAbkmCb8F1IKRJ0p2wll1+v2fLyQIVUkhj/pHHo3MQapRlLQLK+XQKhAozmABvzd+dAMoa5zlJK7EjAFiinnuy6suD+7+NuvYgGi+tCMRUpZAZdyhJboxous+jIBgGzEcrxavG4Mv2J+vkGAwYMQfesJMSYNnhct/JjJd1Oc6DVHSBXH8jQclniNZXltrDzu77McyQNsyxD1Jl42paRo83XR25bwcKe4kwYq0IBvMnkZgzWDp+mQmYjucdiVf53Dngt9Del6OW5tfuyjOCIDMVIq84MxsahsBtXI7/wJ3T9jSubnrFIm8THNRgz1WlmVinNGgdntgUFwJLY7AdIj6TunCcRvlHpiWhFnhjqpPHCRvFiT+sfmAVQuWBzRyeHmiiSgFHaoCQ==
  template:
    metadata:
      creationTimestamp: null
      name: obsidian-credentials
      namespace: personal
