apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: security

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: authentik-redis
    namespace: security
    version: 19.6.4
    valuesFile: values.yaml
