apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/seaweedfs/base

components:
  - ../../../apps/infrastructure/seaweedfs/components/storage
  - ../../../apps/infrastructure/seaweedfs/components/webdav
  - ../../../apps/infrastructure/seaweedfs/components/admin
  - ../../../apps/infrastructure/seaweedfs/components/filer-client-service
  - ./components/ingress
  - ./components/velero-bucket

  # - ../../../apps/infrastructure/seaweedfs/components/maintenance # Uncomment to scale down statefulsets

replacements:
  # Inject the live seaweedfs image into the velero provision Job
  - source:
      kind: StatefulSet
      name: seaweedfs-master
      fieldPath: spec.template.spec.containers.0.image
    targets:
      - select:
          kind: Job
          name: s3-velero-provision
        fieldPaths:
          - spec.template.spec.containers.0.image

