apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-db.yaml
    target:
      kind: Deployment
      name: immich-server
  - path: patch-ml.yaml
    target:
      kind: Deployment
      name: immich-machine-learning
