apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  template:
    metadata:
      annotations:
        # Exclude ML cache volume from Velero volume backups
        backup.velero.io/backup-volumes-excludes: cache
