apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage

resources:
  - ../../../apps/infrastructure/valkey/base

components:
  - ../../../apps/infrastructure/valkey/components/storage
  - ./components/secrets
  - ../../../apps/infrastructure/valkey/components/resource-limits
  # - ../../../apps/infrastructure/valkey/components/maintenance
