# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: obsidian-proxy-setup
entries:
  - model: authentik_core.group
    state: present
    id: obsidian-access-group
    identifiers:
      name: obsidian-access
    attrs:
      is_superuser: false

  - model: authentik_providers_proxy.proxyprovider
    state: present
    id: obsidian-provider
    identifiers:
      name: Obsidian Proxy
    attrs:
      mode: forward_single
      external_host: https://obsidian.ruth.aritrosinha.dpdns.org
