apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
      name: authentik-server
      namespace: security
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: authentik-server
        namespace: security
      spec:
        replicas: 1
  - target:
      kind: Deployment
      name: authentik-worker
      namespace: security
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: authentik-worker
        namespace: security
      spec:
        replicas: 1
