apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: security
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: security
spec:
  replicas: 1
