apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-hyperion-strawslabs-prod
  namespace: networking
spec:
  secretName: wildcard-hyperion-strawslabs-prod-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "*.hyperion.strawslabs.com"
