apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-dummy
  namespace: longhorn-system
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: longhorn-dummy-tls
  issuerRef:
    name: selfsigned-default
    kind: ClusterIssuer
  dnsNames:
    - "longhorn.example.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
