apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-obsidian
  namespace: backup
spec:
  schedule: "30 21 * * *" # 03:00 AM IST (21:30 UTC)
  template:
    includedNamespaces:
      - personal
    labelSelector:
      matchLabels:
        app: obsidian
    storageLocation: aws
    defaultVolumesToFsBackup: true # Global Opt-Out / Per-Schedule Opt-In Strategy
    ttl: 720h0m0s # 30 days
