apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-db-backup
  labels:
    app.kubernetes.io/name: authentik-db-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
