apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  template:
    metadata:
      annotations:
        # Exclude massive media volume from Velero volume backups
        backup.velero.io/backup-volumes-excludes: data
    spec:
      containers:
        - name: main
          volumeMounts:
            - name: db-backup
              mountPath: /data/backups
      volumes:
        - name: db-backup
          persistentVolumeClaim:
            claimName: immich-db-backup
