---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: hyperion-velero-s3
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  template:
    metadata:
      name: hyperion-velero-s3
      namespace: storage
      annotations:
        argocd.argoproj.io/sync-wave: '-2'
        sealedsecrets.bitnami.com/namespace-wide: ''
    type: Opaque
  encryptedData:
    access_key: AgBqs39a8kuTTEQJfcjM9oMpSomEdlwGZfV4EeM6AoNxBicrPDwFSZnRbPNxFh1XTIwImgWmwMTAlCD5TpbLjdTRTGAXVnvh+CboXtFtxDvqVvmTryIh5mzKbi/Fk6yJh/D4rGFE55G1m2rrIXjCay1XqS2kKOz/4fGj7uWzk0ri72xh8RQemSrPQEGIOQ0b7ZaT9dGU/WFtgfbu39+TdRO+p5+9ldV/pTZLlSErmSJi4x9ZUp4wh+YnyNdwMytBiGh7pSVjnwADbbRXGDpSuDdstf78BfkNhOqZi4AbhlEj/jHR5UApSj6K+pEOLyCAUCkgHeuiWDiGxpwDVuxJd2Su+57jU6D9Tky3HfVrmCHHA62U4qrm25fHk6AdDv87qcLFxEVQBdptNZXOlCxdXB65AyyTlQsEauPQPD5pc1C7yHtbFQWBNmOq+/xVxTFP6VnUOiBNO10AC3YLVRTw7TvQ0lSyY65I8DN4LzmAIxq8wlgbhjdyV7Ufh8G7iFtwF7AM2XWfTikp8mjkL2QZYjkq5iYoimOndiCq9k9//8xwmqbEFviOwjqkpjmEbom73hVeHYS3vhRCO8l9tBKThBEdjQzYa7WoUNZ+Ikpo1+WLxkwl3kUKO6gBxHYTfQVX0V1UGn97iR2I8ULgkiIpv+S4JvyQx5BMjbgKG6K340HLsDhX6zODuQSO1qatNN5dGhftPvdXSPluYHwo5nkB1A==
    secret_key: AgAeaj1U4RL9rDvtkk+LB6ENJqKm4qjNvM3CTnKqpsLPAYozleWQ57uT8j01fSz9AHllVTl2rwZMyaIWysWn8yoba5O6SlQohAvCjHOPXzYt8c1CRZLoquv3LdPNnCIcAmvz9LQ0RD902w7+zgJZGp9wYY9QOMC08CGUK4V2CWU05l8QmwUolJ+zwCKDhLA8RT9b4DRii0qUkS0D4NLui3OuLyM9rs56LJCxIfOjm9f/ww5xDisBJWxxqKZ0KqY7y1lfQ6U7hSfEDb8h5+foSmkIaIv+JYODpuJpQkzLXcEeb3udN1JKDRDqdMv9kacfwcV8hZezMqNW2ESOEBipmegvY6KkuqfDe0ftwyEQWKzE7xX+eOrLQdtiJWVWgbA9Ax9ov1LQ2+CiQgv02nM+pM4gaKtN0yDYEi6gXMbsije8+Ilk0s4/qWlQZ9T1WuTrSqxJml0S5kyoJFSrSWXeEOikGwxf5JMB1e10oQRN8nlnFAn5I57YxNDu91skw7Z7yFgH5g6K+lb2njfa61x91MhnpwjayEJy8bDJr4ukHscYSIm+yLh5h8vfPolSV6G5gq3B8I3SG3OlWUyrCtxOYo0o7keS0S4BoqE6clYtAilGV2Q6/7PjUBB69KTgJh+hmYqN/DLoAr6zIqA1gxPOm9avRunxDcaBUgkfk7dic/U83j3czr7fWzNpdr/rEuMM/TKI9MK127tTkW98o7xhWe1e1gqknR9Vrbm76/498M4qEjsk5zrR04Ps
