apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hyperion-velero-s3
  namespace: backup
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: velero-storage-secret-store
  target:
    name: hyperion-velero-s3
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        cloud: |-
          [default]
          aws_access_key_id = {{ .access_key }}
          aws_secret_access_key = {{ .secret_key }}
  dataFrom:
    - extract:
        key: hyperion-velero-s3
