---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hyperion-velero-s3
  namespace: storage
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
spec:
  encryptedData:
    access_key: AgC9tehFroFxcHgSvhgQqKf8ZyLGQdZeUxh486k+D/SywWNCwAmmdjvOQLqZ67ZdSiF34MMoSccH3lFH2kjxXYZp6FY71CjuG1QNOSrDZxYNuo/R9aNWxSGBV8nh4Xq3RJUp+VIJTbBveFRqnQ/dKf9+bRME8XfAk/5clWolxTSTbxRpeM3LW6ye6K7Df3kGUaEQX1Q/vwvljD30IbukccIkrMGTRfxmq0+ypwXO8rXbVtAlNASi1Ln6ENdKRcmTEKE7V/A8HRnFj3BrBFjrLdnQVfGw/kx5KW6dj01RiBChnyJDwLX/KlQrRXmpbDvf/5WIRNsxqLmr8fa09uVoABcJNRfqtP+eUXtd8v7w/lWAI7IqTL1Y1TsmADjSUzk6pXSODy6gtTcr6lDhCdpVpdj9y6eAPrlpkbdh4mPG7TrFrxMvho980LkKCyJEv0TJ39/XFW8FseslkocYmISc/A9b0Je/XmFubsJuXHBCKCoDsvF3EpkhVAhyaD5orI5iLXDTSJAhWwg9HcaVWCx5vXZLkPPqzQlNCMr2Tx69qqmLvLuFcz04IDQymSERGvUYTDxBKwMzp45B8OELQcaIU8ZT7TLYGQgpZmsZF8IufKxvvpUdjKx/r02sIvT/WvlwgDfry6KPyWWmbYzu+i40WLO13gL4WoX9x1BzupT8bAUZNwmer+Uqyl1iIGMw9f2jjCLuezyAoYk0PdPAT5ivYkuT4ePAfw==
    secret_key: AgABQu4Zhy+wYfTa8ODgW6dFD8WJ7NMqWSF7WHGMMwZnr1hH6Pxm/DZWBY6mzQ6KqHM4eg2CU5S0NPX8xdR7TAUnwDI8BQ8pyG2ADLFm+/WzCSTTWuST2eWTvFf+Nu7e/zUSDH26zMOLojpQA5OesZtMF/4ZPTwFqbyCZVIagHMwIJtS4nOpEFbaJyewbzUFIQDmEwHZltOHQuUFen2/FmzY6YRqIREjlw/XmrWDZqpV36lm4eF3nOVOnc4SW2VQuddT9aZ0LBPK7mYPRG8SAnE88gyzRitGDEE+vnvOSl5NZDG2UYE6d4oSmP1KP4Y+tdUBiVPS+/l+fZI6miappT5w+YUKcoctqIqSU0PnaJZIrm4GXSMe/H3M4TOagjp0ijpGUaKY4KQUi/vICYw3sLxqUOAkU4X6op7XBMy1Sy2hjbK5FqM1W87eNJtnzt6uvl1J8MwQbLEyw98wKmxiWyfpUgT2nrAhbrJc3vLrQRXVjM708MBUep8+rKpOGK8td5CWZjdgbcnKuPX9Byl+MxNHhDKEFFnsBBadnud7SqNR4b2ncSKnrXjA40gYsQYgPT0ExVatzS3Bc1uo58/RyghYm5ElLp7cRVEydg94aD7X6bPkIN5JrbiNrzP6coidjPyi1lMyDOiEZODot/e+UFvX3t7ZstlCo+y7prE7R758pDcncO7QrOJ9V2uY6JHKwCFGOl8ETja3UNxGmX1LMkf7zJCh8r/c4w3BBDv73CjekAFl12pzKKk2
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
        sealedsecrets.bitnami.com/namespace-wide: ""
      name: hyperion-velero-s3
      namespace: storage
    type: Opaque
