---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-aritrosinha
  namespace: networking
spec:
  encryptedData:
    api-token: AgDaNJCJT/JO7Yg5xB6aRs7hbv5oPm+f2ijlq+TRNS7xlsmMwrBtzDyJUQTsWvb3+AOT8Vs4bGD6EYBxSr8D4nTJiaaq590ulVNmLfxAXfgU1u/2EccpV7QqsZSKuVvq2VRJ9+uoBH16rG86TKRxYApfatoe1EAyjUxHUvD8OGxE53rIV4lKNDmpmZOCf0+JwLnNXMFW8RlJcHkP85woKKo4wU6e351YGXY7LEWAjME4w07UkCbAnpTZgtgjjIa9b5vrptJ0SsZyOtEajqLuUPu6OrVQzf/tLSLNqaS9Tff+rbquzmiRoPI8Yz+GnRaQ0oai4R98f8QGhLQBWmDdQJAfija6D3OxYT3Oz6+RjCR+XW8M+gQRZqTbo2LKzYX0lqKgByzHGEkdXturo9kQ6jzJIyLpo2CsByq+6JjhTNfq/1thq5kp/njIkXhlTnJUxJbXK/+/l/dWn5BS60aB31LnHXdkKU28kdsQiBN8AH9Ra8hZhaKsPAI6AzxuN6zznof3B6+DNKMMh7dmi5fWe7+MCe+0r6tErr2OI+50DkHGv0L//fKR1Vmh/p/NDHovznD9IZlWQPUGqgbCfIk+YLMYLeMXL7q5r/glQOhzK5o+yUP+9eXm2BZ0AfmjY2RxTvTDMRjHhs82M3UXbxgl6+8aK3uIp3tuTXGTXk4apF5hgxOSe77j6VYZiynjnlfGE6oIwaQ2MZ+wWl0wiByowBsM+wkcXwkDfD1gplSbaIetRsOk5soRam+3G/bjudeUAHBLMdp/Ew==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-aritrosinha
      namespace: networking
