---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns-aritrosinha
  namespace: networking
spec:
  encryptedData:
    api-token: AgCgmzdObdlppi2/GmZFo+u0/1BjyfTqbs8Hn8tpo32oBwUPE5OBPNOOEQEEIGiVNBLWllUmbyugcWiBZQVtRuUdeBosy6eUbMh45qlYo74rThB2F7dLqD/qZhNFB3rsoHkZVg3lzIIbJNXZImjRHwodRJoQDSJpHFOBBp7tXovG4L6qgPHqu8mb/7s9WVr/Jbqa2BxFtS1VSFTDG1y5TlVcSq12H1YokDp6XN7e9CP1a9bq1NR5HbZZhoP6AD9/mVnmtxjzpT5psMuMYe1idW41o0h2vguVB+UDxl3PmQAJ2f7Jmy5uzprRkpxeUyFxyL+/S0gCaN/27Hu9uM2QwVDf5P1s3+7nZojtKyQalCeVkN2GiitkB9ZVDk07S03brbeMdJPIRBa8qW4QeQnvu7clxqljlAUxnWxOtU8Xw3cmIphXDB+EW8XoT64ExFcPcS1RURo4DBkuvJyMJ2ekxQxxmJRtxJfEJOr10k0GCSkNwvyd+BRqkvXtooI5JwPEehIqsdqxNIdzdAIhxBM7UjehbDxL+lm6Kh4W2z2MQFtmbn8mlzHBncDSwj2FVBUFVq+sEpMKDO42H1RSNzKd/xwMrR5GlWf/t0dQ5MYyy8BLAFfVHntyr68vaHxu7dGB8tQZb50Dfyn4TNMf6jWjt7xZ7zBlynFiHtP11z48vXKsg9xPLRm7TCaiPNXv/C+UrQmurS3r+Z5/f8269c+L/5C9j7hCMHsKmxJocCk60DKal7frgz7KYBUPZAvdaq039KopHXYo2Q==
  template:
    metadata:
      name: cloudflare-dns-aritrosinha
      namespace: networking
