---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-aritrosinha
  namespace: networking
spec:
  encryptedData:
    api-token: AgAVm4MCRNmbRyo6j1yd41OKE3qYwnERTGwJi/NDAuaTwmXeWbU/nO9cJoFpSnCQ1nAUmjcwNgZ/cVUUavCS06CAKN/Q4AE+FDkAw6VvFboxsPKSTVhH9WwE5qcgYFlOuUGijmns6y9xa0Z7qRVMqURLLaUHS+BpTXFYUr3HcLnb6nulzlq/YHq8qhsr04g3pcCkFbkp1x52A3S81NB4Zs8xVyX45b2I3iiaq4Uu2KF0aRShGQQbqfDVBkPWOzfBjU8N8kGCtPxxgDVljdrJL+kuIPcn5yG1DXD1hzOQp+Xph3HEFxEqU4PrwRpkyhsyaxuiqLukcqwv2yOZAr0WNEObVjHsrantQPdnRxTgGvUpHZkd6Ed1d5P0ZK+sSvZwVHywpcI6auaS9I2XC0dM1qo2oAX/SD60vJTHlCH8Iy5LP0oVa7bFu1kfc+a61tAWDn1k7P/a89wekpI3/CXnIDaE5gKPSZ1Vlwjrt8OKNx/7xlxdAXKHn89Lmb9fs6b+xzSazZIGqNgmnkMWhhh8gJNhOW+BipslfPdCW1mHPTnjKuL6B6ZlP7OBJtI1tZMQtkOVcB/uIcVMI4wvCfWsIDw7gPsaBCEfn5/yG2P/0oFFHJvDo3gLk9mCEx63HYa8jwLrYx4A6CWe5L6nrQIh5fK8mK3Z7532PDsBc1Nac9l/CHluuj39d3cqVbeAkxawnMdHpdoZ3WZzHlFY8qPoX2+gcUEDm/3AYkOYuy/jb0bkIZpI5AESohZzlv2qG3kCAzza3vptLg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-aritrosinha
      namespace: networking
