apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

helmCharts:
  - name: redis
    repo: https://kubelauncher.github.io/charts
    releaseName: redis
    namespace: security
    version: 0.2.14
    valuesFile: values.yaml
