apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-service-accounts
  namespace: storage
type: Opaque
stringData:
  alertmanager-access-key: "alertmanager"
  alertmanager-secret-key: "alertmanager"
  admin-access-key: "admin"
  admin-secret-key: "admin"
