apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-service-accounts
  namespace: storage
type: Opaque
stringData:
  mimir-access-key: "mimir"
  mimir-secret-key: "mimir"
  loki-access-key: "loki"
  loki-secret-key: "loki"
  alertmanager-access-key: "alertmanager"
  alertmanager-secret-key: "alertmanager"
  velero-access-key: "admin"
  velero-secret-key: "admin"
  admin-access-key: "admin"
  admin-secret-key: "admin"
