apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: personal
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: personal
spec:
  replicas: 1
