apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
    spec:
      containers:
        - name: obsidian
          image: lscr.io/linuxserver/obsidian:v1.12.7-ls138
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: https
          env:
            - name: PIXELFLUX_WAYLAND
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Kolkata"
            # Managed via Authentik Forward Auth
            - name: AUTH_CONFIG
              value: "None"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: obsidian-config
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
