apiVersion: v1
kind: Service
metadata:
  name: obsidian
  namespace: personal
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: https
  selector:
    app: obsidian
