apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking

components:
  - ../components/authentik-middleware

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 41.0.2
    releaseName: traefik
    namespace: networking
    includeCRDs: true
    valuesFile: values.yaml
