# meta/main.yml
---
galaxy_info:
  author: Aritro
  role_name: bun
  namespace: internal
  description: Installs the Bun JavaScript runtime and package manager.
  company: None
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - bun
    - javascript
    - runtime
    - development

dependencies: []
