apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    releaseName: velero
    namespace: backup
    version: 12.0.0
    valuesFile: values.yaml




