image:
  repository: docker.io/velero/velero
  tag: v1.18.0
  pullPolicy: IfNotPresent

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

upgradeCRDs: true

# BSL/VSL defaults are removed. They are injected by Kustomize components (e.g. s3-seaweedfs or s3-aws)
configuration:
  backupStorageLocation: []
  volumeSnapshotLocation: []
  defaultVolumesToFsBackup: true

deployNodeAgent: true

# schedules: {}



rbac:
  create: true

serviceAccount:
  server:
    create: true
