apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-master-aritrosinha
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-master-aritrosinha-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "seaweedfs.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-filer-aritrosinha
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-filer-aritrosinha-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "filer.seaweedfs.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-s3-aritrosinha
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-s3-aritrosinha-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "s3.seaweedfs.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-admin-aritrosinha
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-admin-aritrosinha-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "admin.seaweedfs.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-volume-aritrosinha
  namespace: storage
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: seaweedfs-volume-aritrosinha-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "volume.seaweedfs.hyperion.aritrosinha.dpdns.org"
    - "*.volume.seaweedfs.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"
