apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-master
  namespace: storage
  labels:
    backuplabel.certificate: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "seaweedfs-hyperion.strawslabs.com"
      secretName: seaweedfs-master-tls
  rules:
    - host: "seaweedfs-hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-master
                port:
                  number: 9333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-filer
  namespace: storage
  labels:
    backuplabel.certificate: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    # link.argocd.argoproj.io/external-link: "https://filer.seaweedfs-hyperion.strawslabs.com/"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "filer.seaweedfs-hyperion.strawslabs.com"
      secretName: seaweedfs-filer-tls
  rules:
    - host: "filer.seaweedfs-hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-filer
                port:
                  number: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-s3
  namespace: storage
  labels:
    backuplabel.certificate: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "s3.seaweedfs-hyperion.strawslabs.com"
      secretName: seaweedfs-s3-tls
  rules:
    - host: "s3.seaweedfs-hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-s3
                port:
                  number: 8333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-admin
  namespace: storage
  labels:
    backuplabel.certificate: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    # link.argocd.argoproj.io/external-link: "https://admin.seaweedfs-hyperion.strawslabs.com/"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "admin.seaweedfs-hyperion.strawslabs.com"
      secretName: seaweedfs-admin-tls
  rules:
    - host: "admin.seaweedfs-hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-admin
                port:
                  number: 23646
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-volume
  namespace: storage
  labels:
    backuplabel.certificate: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "volume.seaweedfs-hyperion.strawslabs.com"
        - "*.volume.seaweedfs-hyperion.strawslabs.com"
      secretName: seaweedfs-volume-tls
  rules:
    - host: "volume.seaweedfs-hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
    - host: "*.volume.seaweedfs-hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seaweedfs-volume
                port:
                  number: 8080
