apiVersion: v1
kind: Secret
metadata:
  name: seaweedtest-s3-service-accounts
  namespace: storage-test
type: Opaque
stringData:
  mimir-access-key: "sa-mimir"
  mimir-secret-key: "mimir-secure-s3-secret-key-2026"
  loki-access-key: "sa-loki"
  loki-secret-key: "loki-secure-s3-secret-key-2026"
  alertmanager-access-key: "sa-alertmanager"
  alertmanager-secret-key: "alertmanager-secure-s3-secret-key-2026"
  velero-access-key: "sa-velero"
  velero-secret-key: "velero-secure-s3-secret-key-2026"
  admin-access-key: "admin"
  admin-secret-key: "admin-secure-s3-secret-key-2026"
