apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: CHANGE_ME-secret
  namespace: logging
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: loki-storage-secret-store
  target:
    name: CHANGE_ME-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: CHANGE_ME-secret
