apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-read
spec:
  template:
    spec:
      containers:
        - name: read
          env:
            - name: S3_ENDPOINT
              value: "http://seaweedfs-s3.storage.svc:8333"
            - name: S3_REGION
              value: "us-east-1"
            - name: S3_BUCKET_CHUNKS
              value: "CHANGE_ME-bucket-chunks"
            - name: S3_BUCKET_RULER
              value: "CHANGE_ME-bucket-ruler"
            - name: S3_BUCKET_ADMIN
              value: "CHANGE_ME-bucket-admin"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: CHANGE_ME-secret
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: CHANGE_ME-secret
                  key: secret_key
