apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian
  namespace: personal
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: obsidian.ruth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: obsidian
                port:
                  name: http
  tls:
    - hosts:
        - obsidian.ruth.example.com
