storageClass:
  create: true
  name: nfs
  defaultClass: false
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: false
  accessModes: ReadWriteMany
  volumeBindingMode: Immediate

nfs:
  server: ""
  path: ""
  mountOptions:
    - hard
    - noatime
    - actimeo=2