nfs:
  server: "192.168.0.2"
  path: /WD4TB/shared/v1
  mountOptions:
    - hard
    - noatime
    - actimeo=2

storageClass:
  create: true
  name: nfs
  allowVolumeExpansion: true
  reclaimPolicy: Retain
  archiveOnDelete: true
  accessModes: ReadWriteMany
  volumeBindingMode: Immediate