apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/postgresql-14/base

components:
  - ../../../apps/infrastructure/postgresql-14/components/secrets
  - ../../../apps/infrastructure/postgresql-14/components/storage
  - ../../../apps/infrastructure/postgresql-14/components/resource-limits
