apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-ssl-certs
  namespace: backup
spec:
  schedule: "30 21 * * *" # 03:00 AM IST (21:30 UTC)
  template:
    includedNamespaces:
      - networking
    storageLocation: aws
    ttl: 720h0m0s # 30 days
