apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.6.2
    releaseName: kyverno
    namespace: security
    includeCRDs: true
    valuesFile: values.yaml

namespace: security

resources:
  - policy-exception.yaml
