apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: personal
spec:
  template:
    spec:
      containers:
        - name: main
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: personal
spec:
  template:
    spec:
      containers:
        - name: main
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
