---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-aws-creds
  namespace: backup
spec:
  encryptedData:
    cloud: AgCGvzMqLRvEaogHNHlAWEWpQt20XL0PTT0MAs3HZ+YdkUEfKAfcQCDGQRyKcvgNp8+H14rpwe956SgB9Z0HJ1kDBHiS6jYn1Y8LH1176MSZbkHFLSlkC00Xo1dz7AMFRW1SawhkhbC1bhdGY/pQn6I9Z/SwuyAL/WXaH0oe2toomi1l9oZOLPyw+hZdyibKlto5k/wAx0qHXSDYtnJP1cXBatBgfeL8Bd9U29KteO3Low28l+3otZHxLJ4kDwrXJuRIYEhNhBitmaUf8L+WJc6ScfSbjixdum0YNMLEZWQnFxQUjHBFFRTUzcp3rnyU/X9OzwM/g9nPVOcEbVhQrW8bPgbUnPHOL1Af3Qd+BVlLXT9IHoPF20R2uIfD5uRwuMRExaN4dXs7R/KHRMMcQx6gE+N1VbPcNMZ/MStooJWr75fBrjQfImo/XcmtG8cReuBMma/BGqsm+uviqiaJNvhLrW8LIsgsb5qZ6p/Bj6eQXIV+TMg10sqbdmtP35AkxgzKazqDl3HgyXGva33/Fchg5q59NIn9hKX4M5eiioHW9ewhdpxGjcKmAmdXS0SRLRyU7irDllnVwZRdqwTFUSTH9Oo6VUSwfbVGiUVM4EGVlaBOb+Tb/IzlV5mZPumt0Ty8cI3rIE9oNos8KlD1QJ0zyWgzZ4WlOHBz1GyMFiyiP18OcyojCwWSzmOrRD08JLc79ZCwF7pPqU8Vq/x715HNb8fjXxr6RqHJoGV5o22R3G7lRWDL+3h/aqssOwTcVoVsFtaFfiuOtblAnvPgYADRSnMJU3fIy7P/HhWkxsCM97ydEHmI4TnKc47kX7FDwmqdKU6kpp/1kT4Qvx+caFj+bEyUhw==
  template:
    metadata:
      creationTimestamp: null
      name: velero-aws-creds
      namespace: backup
    type: Opaque
