apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-aritrosinha"
spec:
  tls:
    - hosts:
        - "grafana.hyperion.aritrosinha.dpdns.org"
      secretName: wildcard-hyperion-aritrosinha-prod-tls
    - hosts:
        - "grafana.hyperion.strawslabs.com"
      secretName: wildcard-hyperion-strawslabs-prod-tls
  rules:
    - host: "grafana.hyperion.aritrosinha.dpdns.org"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
    - host: "grafana.hyperion.strawslabs.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
