alloy:
  clustering:
    enabled: true
    portName: http

  stabilityLevel: "generally-available"
  storagePath: /var/lib/alloy/data

  enableHttpServerPort: true
  listenAddr: 0.0.0.0
  listenPort: 12345
  listenScheme: HTTP

  uiPathPrefix: /
  enableReporting: true

  securityContext:
    privileged: true

  mounts:
    varlog: true
    dockercontainers: true

controller:
  type: "daemonset"
  enableStatefulSetAutoDeletePVC: false

service:
  enabled: true
  type: ClusterIP
  internalTrafficPolicy: Cluster

serviceMonitor:
  enabled: false

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - alloy.local

rbac:
  create: true

serviceAccount:
  create: true
  automountServiceAccountToken: true

configReloader:
  enabled: true
