apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert-strawslabs
  namespace: security
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: authentik-cert-strawslabs-tls
  issuerRef:
    name: letsencrypt-prod-strawslabs
    kind: ClusterIssuer
  dnsNames:
    - "authentik-hyperion.strawslabs.com"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"