apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager-metrics
  namespace: networking
  labels:
    release: mimir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  namespaceSelector:
    matchNames:
      - networking
  endpoints:
    - port: http-metrics
      interval: 15s
      path: /metrics
