apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
      name: traefik
      namespace: networking
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: traefik
      spec:
        replicas: 1
