apiVersion: batch/v1
kind: Job
metadata:
  name: immich-init-db
  namespace: personal
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: postgres:14-alpine
          command:
            - /bin/sh
            - -c
            - |
              export PGPASSWORD=$DB_PASSWORD
              # Check if the database exists; if not, create it
              psql -h postgresql-14.infrastructure.svc.cluster.local -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'immich'" | grep -q 1 || psql -h postgresql-14.infrastructure.svc.cluster.local -U postgres -c "CREATE DATABASE immich;"

              # Apply the vectors extension
              psql -h postgresql-14.infrastructure.svc.cluster.local -U postgres -d immich -c "CREATE EXTENSION IF NOT EXISTS vectors;"

              # Initialize storage structure
              echo "Initializing storage structure in /data..."
              mkdir -p /data/library /data/upload /data/profile /data/thumbs /data/encoded-video /data/backups
              for dir in library upload profile thumbs encoded-video backups; do
                touch "/data/$dir/.immich"
              done
              chown -R 1000:1000 /data
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgresql-secret
                  key: password
                  optional: true
          volumeMounts:
            - name: library
              mountPath: /data
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
      restartPolicy: Never
  backoffLimit: 2
