# tasks/main.yml
---
- name: Install Git (Debian)
  ansible.builtin.apt:
    name: "{{ git_packages }}"
    state: present
    update_cache: true
  register: git_apt_install_status
  until: git_apt_install_status is success
  retries: 10
  delay: 5
  when: ansible_facts['os_family'] == "Debian"
  tags: [git, packages]

- name: Install Git (Alpine)
  community.general.apk:
    name: "{{ git_packages_alpine }}"
    state: present
  when: ansible_facts['os_family'] == "Alpine"
  tags: [git, packages]
