# tasks/main.yml
---
- name: Install Git (Debian)
  ansible.builtin.apt:
    name: "{{ git_packages }}"
    state: present
    update_cache: true
  register: git_apt_install_status
  until: git_apt_install_status is success
  retries: 10
  delay: 5
  when: ansible_facts['os_family'] == "Debian"
  tags: [git, packages]

- name: Install Git (Alpine)
  community.general.apk:
    name: "{{ git_packages_alpine }}"
    state: present
  when: ansible_facts['os_family'] == "Alpine"
  tags: [git, packages]

- name: Configure global Git user name
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global
  environment:
    HOME: "{{ git_user_home }}"
  become: true
  become_user: "{{ git_user }}"
  when: git_user_name | length > 0
  tags: [git, config]

- name: Configure global Git user email
  community.general.git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
  environment:
    HOME: "{{ git_user_home }}"
  become: true
  become_user: "{{ git_user }}"
  when: git_user_email | length > 0
  tags: [git, config]
