apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: ConfigMap
      name: alloy
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: alloy
      data:
        config.alloy: |
          // Logging: Discovery
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "keep"
              regex = ".*"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label = "node"
            }
          }

          // Logging: Source
          loki.source.kubernetes "pod_logs" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.write.default.receiver]
          }

          // Logging: Write
          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.logging.svc.cluster.local:80/loki/api/v1/push"
              tenant_id = "1"
            }
          }

          // Metrics: Discovery (Node Exporter)
          discovery.kubernetes "nodes" {
            role = "service"
          }

          discovery.relabel "node_exporter" {
            targets = discovery.kubernetes.nodes.targets
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = ".*node-exporter.*"
              action = "keep"
            }
          }

          // Metrics: Scrape (Node Exporter)
          prometheus.scrape "node_exporter" {
            job_name   = "node-exporter"
            targets    = discovery.relabel.node_exporter.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (Kube State Metrics)
          discovery.relabel "kube_state_metrics" {
            targets = discovery.kubernetes.nodes.targets
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = ".*kube-state-metrics.*"
              action = "keep"
            }
          }

          // Metrics: Scrape (Kube State Metrics)
          prometheus.scrape "kube_state_metrics" {
            job_name   = "kube-state-metrics"
            targets    = discovery.relabel.kube_state_metrics.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (SeaweedFS)
          discovery.kubernetes "seaweedfs_services" {
            role = "service"
          }

          discovery.relabel "seaweedfs_svc" {
            targets = discovery.kubernetes.seaweedfs_services.targets
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = ".*seaweedfs.*"
              action = "keep"
            }
          }

          // Metrics: Scrape (SeaweedFS)
          prometheus.scrape "seaweedfs" {
            job_name   = "seaweedfs"
            targets    = discovery.relabel.seaweedfs_svc.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (Traefik)
          discovery.kubernetes "traefik_services" {
            role = "service"
          }

          discovery.relabel "traefik" {
            targets = discovery.kubernetes.traefik_services.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "keep"
              regex = "networking"
            }
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = "traefik.*"
              action = "keep"
            }
          }

          // Metrics: Scrape (Traefik)
          prometheus.scrape "traefik" {
            job_name   = "traefik"
            targets    = discovery.relabel.traefik.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (cert-manager)
          discovery.kubernetes "cert_manager_services" {
            role = "service"
          }

          discovery.relabel "cert_manager" {
            targets = discovery.kubernetes.cert_manager_services.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "keep"
              regex = "networking"
            }
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = "cert-manager$"
              action = "keep"
            }
          }

          // Metrics: Scrape (cert-manager)
          prometheus.scrape "cert_manager" {
            job_name   = "cert-manager"
            targets    = discovery.relabel.cert_manager.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (MetalLB)
          discovery.kubernetes "metallb_services" {
            role = "service"
          }

          discovery.relabel "metallb" {
            targets = discovery.kubernetes.metallb_services.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "keep"
              regex = "networking"
            }
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = "metallb-.*"
              action = "keep"
            }
          }

          // Metrics: Scrape (MetalLB)
          prometheus.scrape "metallb" {
            job_name   = "metallb"
            targets    = discovery.relabel.metallb.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (external-dns)
          discovery.kubernetes "external_dns_services" {
            role = "service"
          }

          discovery.relabel "external_dns" {
            targets = discovery.kubernetes.external_dns_services.targets
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action = "keep"
              regex = "external-dns"
            }
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = "external-dns$"
              action = "keep"
            }
          }

          // Metrics: Scrape (external-dns)
          prometheus.scrape "external_dns" {
            job_name   = "external-dns"
            targets    = discovery.relabel.external_dns.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "15s"
          }

          // Metrics: Discovery (Velero)
          discovery.relabel "velero" {
            targets = discovery.kubernetes.nodes.targets
            rule {
              source_labels = ["__meta_kubernetes_service_name"]
              regex = "velero.*"
              action = "keep"
            }
          }

          // Metrics: Scrape (Velero)
          prometheus.scrape "velero" {
            job_name   = "velero"
            targets    = discovery.relabel.velero.output
            forward_to = [prometheus.remote_write.mimir.receiver]
            scrape_interval = "30s"
            metrics_path    = "/metrics"
          }

          // Metrics: Write
          prometheus.remote_write "mimir" {
            endpoint {
              url = "http://mimir-gateway.monitoring.svc.cluster.local:80/api/v1/push"
              headers = {
                "X-Scope-OrgID" = "anonymous",
              }
            }
          }
