# defaults/main.yml
---
# Kubernetes Version (Must be in format vX.Y)
# This controls which repository is added.
k8s_repo_version: "v1.31"
_k8s_repo_version: "v{{ k8s_repo_version | regex_replace('^v', '') }}"

# Paths
k8s_repo_k8s_keyring_dir: "{{ k8s_keyring_dir | default('/etc/apt/keyrings') }}"
k8s_repo_k8s_keyring_file: "{{ k8s_keyring_file | default('kubernetes-apt-keyring.asc') }}"
