apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: copyparty-tls
  namespace: copyparty
  labels:
    backuplabel.certificate: "true"
spec:
  secretName: copyparty-tls
  issuerRef:
    name: letsencrypt-prod-aritrosinha
    kind: ClusterIssuer
  dnsNames:
    - "copyparty.hyperion.aritrosinha.dpdns.org"
  secretTemplate:
    labels:
      backuplabel.certificate: "true"