apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/services/immich/base
components:
  #   - ../../../apps/services/immich/components/init-db
  #   - ../../../apps/services/immich/components/ingress
  #   - ../../../apps/services/immich/components/storage
  - ../../../apps/services/immich/components/resource-limits
  - ../../../apps/services/immich/components/replica-count
  # - ../../../apps/services/immich/components/maintenance
