# defaults/main.yml
---
# Networking
kubeadm_cluster_kubeadm_pod_network_cidr: "{{ kubeadm_pod_network_cidr | default('10.244.0.0/16') }}"
kubeadm_cluster_kubeadm_service_cidr: "{{ kubeadm_service_cidr | default('10.96.0.0/12') }}"
kubeadm_cluster_kubeadm_control_plane_endpoint: "{{ kubeadm_control_plane_endpoint | default('') }}"

# CNI
kubeadm_cluster_calico_version: "{{ calico_version | default('v3.27.0') }}"
_kubeadm_cluster_calico_version: "v{{ kubeadm_cluster_calico_version | regex_replace('^v', '') }}"
kubeadm_cluster_calico_manifest_url: >-
  {{ calico_manifest_url | default('https://raw.githubusercontent.com/projectcalico/calico/' + _kubeadm_cluster_calico_version + '/manifests/calico.yaml') }}

# Bootstrap Logic
kubeadm_cluster_kubeadm_bootstrap_node: "{{ kubeadm_bootstrap_node | default('') }}"

# Safety Switches
kubeadm_cluster_allow_destructive_reset: "{{ allow_destructive_reset | default(false) }}"
