apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-dummy
  namespace: monitoring
  labels:
    backuplabel.certificate: "true"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - grafana-dummy.example.com
      secretName: grafana-dummy-tls
  rules:
    - host: grafana-dummy.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80