apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

resources:
  - ../../../apps/infrastructure/postgresql-18/base

components:
  - ../../../apps/infrastructure/postgresql-18/components/secrets
  - ./components/secrets
  - ../../../apps/infrastructure/postgresql-18/components/storage
  - ../../../apps/infrastructure/postgresql-18/components/resource-limits
  # - ../../../apps/infrastructure/postgresql-18/components/maintenance
