apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-admin
  namespace: personal
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-5"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: immich-storage-secret-store
  target:
    name: postgres-admin
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: postgres-admin
