apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  template:
    spec:
      containers:
        - name: main
          env:
            - name: DB_HOSTNAME
              value: "postgresql-14.storage.svc.cluster.local"
            - name: REDIS_HOSTNAME
              value: "redis.storage.svc.cluster.local"
            - name: REDIS_PASSWORD
              value: "change-me-please-redis-password"
            - name: REDIS_DB
              value: "1"
          envFrom:
            - secretRef:
                name: immich-db-credentials
