---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secret
  namespace: personal
spec:
  encryptedData:
    DB_PASSWORD: AgBKbPc7GbYXiC9F+nr3/k7CFaOkRgILkFzFziz5ZWtP24rEyF/vuy3568wyjD3mMvOtu1uUxPOdGTyDFfMbLzVc4lYxQEwA3iMmT+V+eQ43hes6SmSTVVDaAVck/WmyRqyMJLZGWbfS/7Nn8ufNkCcNy2FiTeXIhKdedF/TgNCdO6OgjjHVjOlipaPYYhMiiHVNaz+zhIfipPv8dC+nvAoE1P21MT6fSr6HMxqbbOahBeFP3NWt8lyc+3rHAy5u+FIE7sHvN1qGo2CAmH4z9pcQwGVXiYBejlEiTjlZy+PqrUl1PITYS84okUDx0obYNN/kBjRLZY9KpCHcqUuVO+JA0APxVtZGjsXEbR1jdehuyIxov9nrJhYE8d8UAV/fBrGbaS7D34m6mAtc3loqi30vl43c9Jsq0jWV/tCGCBcLqTB1E1IYBkICV3PWvOBTd3A0Own4fwhL7x+YzrUnHhCTAKCU092ZXnyZ9QBGJgND47Vai2B/TipgYTFyoWxPiPvjyeT+ZSVHxvwPsVAo4eFbhg3BBZgIJPH49L4KbCq97JL4Ewhzrv4EBcy0Hudc8Y98OVDNQ7DV2OmIHGVT8w/oDYOXC7u2phpmc7ExD3N2PBp3hSYzR+u+HK/UPniik2Y/bOFK5AoFLF6QJ+gN2kA+um4RgvRi69lmWF+1kEp+3F8LjZMR0o8mwiP8kK+E+QPrM/rA+Pr5ucH5y/N7Vj4Y6gJKd9ms8cCT0cfm5oSDGdGt
    REDIS_PASSWORD: AgCIItsC1+LjI2AeEyhWalJV5dl1sM6J/eHYM2Fh/jGLijhsPt8qeRywrhkejAV8CFOeusn8blFtAtrTBVJhKeQ/OIQ5NRfkpfw5QzzFfHDSra/goel+CbAbeL7foKRF8O5afmNyuYSmwJjM39WuAPsokcH9E9j9Elg+PVUOwUF1veLJCoEESSsEv4g+qmQxBXaDGGf72pCgEGNNI7X25Fa151gjSo52PY5vYnXHagkhhMLp16h7Zvr+zF/zM7eYvPjbeQGLCSNwUCj3wHTlwaXG3VT96eljnManvhI7KhQLO+AxSVFftw6x3jOfy46/gE0nEqIx63FXxgj9AGdZwe6Q+76weIAXgfdZ3OnWgYaUL5JuomkUQlFsGuH6q8Zbi7qOL8F9lMMPfJ66Bgv/R0uwmpw9rDIIX47sc8IOfG2V0zu6rbPiitYDOfgfAivkZV6dhsRI0oF2fT6krDPBO2N5zpRjfIWqXuwrU0+K5W5xNYxf+pTU0fgMCh8prXkhKly3wP3jbC5FbpwL41rCDLIIR9F096oC8Na/OpgTtFxI/0lQC877cgCi8JpnOxHi7tyn6Xr1em3hY01aT8cQpCOIfdVU9U/0wzTZO8YmNAcch5yFYGXhC6xPiaqeDuu35bKQ6TafqksjksXTTB+hOlby+T/hTOlpCih58gU9B1cZ6v7t9SyvxlTK0zLmy3DM5hARWRt6EB5SEKefok03iEZdD0dukW2AGB0OPUkv9uKR
  template:
    metadata:
      creationTimestamp: null
      name: immich-secret
      namespace: personal
    type: Opaque
