apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-oauth-immich
  namespace: personal
  annotations:
    platform-stack/mirror-to: "security"
spec:
  encryptedData:
    IMMICH_OAUTH_CLIENT_ID: AgAH3pD8sDoDyii08uWbp94HjkKjMg3lxYsl2VU8X72jFmzt4zeHsMU1iIXlEW2+4pNHCk2qQaH2ycM34rctZPGD9hW3F3o3qJZW1HA67tP4zDyKg9GSPpq09JjIy96Pin2TcvigCJr1OaogpuAFqb0zOPtKJiS9SavL/tNWxmvjQK2QKixdF59O5PSoK9f2Jo3jFfdXCTdnB37KGvKs83vcmW0wHdykClNPP+IokE3arprk1Kuga51vjQIgGv+Mdp3wm4WMoDpBKNjWBkt7Rwb2aRe0wS9ZYFA9woXjEV2j4N5ZWuyoNQCFUyx8UPOloJy3BTjWSDKMl+vY7x67BdQThuucuGF8LRzEgSI5APh8LDwCq0dl8XqFXAkPlltaJNc9YUXWOJhGIRGx5MinQEdG8CRonqkca7iF/zFhJIXm+vEVEAYpegtpN8UBM32hA7lu9+uyUejMsyXKIQkoiNeVtpOh05owz8Hp9yFYMTyPnq0Tkp0ngALgamK6HOdVQ80TkfY59twVDfWQwV1h+FfhwVNetCiCOYfDkRsu+BbXVbAMV/eu/UOUZNaQuphOX+baW4tTStBkFKm70+gn1hKisDSvUVOv3CckOa8asFsdn2IlTRSczS7KUizM6wpf4f6uT/3jowZjNJ5KovCdOljdjPGwKGphAXeBORlY1KtwyvaWbShBPtT1EWSmUd3ZIaHBKJRuMXg=
    IMMICH_OAUTH_CLIENT_SECRET: AgCo9+rhNT2ecyHNpuSCMdlh3zh0GbRhLIDeQDyLahE55nCHL/IEfx6Pv1W+KGmJmQKCfX232G7iORttE/dlblhQ6tBvk+8zwUTcMwpcqAJ3zLetMh9l6cYOFLGmCUAEPhQd8+QoT9mFT2u6WLmLSscwuN/RLa3qjChXnIjAk9v9Sk4/HXGYBfUn+XAoveNnq5/17hMV6fY76CFhKYLjr8pTtRVpOwFGsKCu7uE51RvzJVsQMOGv1VO4JOhT2W/aqHTwAKUrCa4a9DD4upiV3W/5skTbFKf4h/mOJ3YjX4TC6umS7CDRNK370FLIEr8Duo7j+t9mkO0o2vS8jS3yjrzv5igBFtrMp1yc7ky4dTwDJRL80xIeZ5EceOktyEcI7y2QXTx7M+Y+9SnL+GXKr7gNq0j+RMVSKig0p5KjUFSlC2Dt73NROWGI+o0YN3V1d+xsRQ6lusiIiXA1dVSbguEFir8JivWAn5YsbP6raNQNNrWvV/Yw6kOYvByBkkhc2CfW17zP6193lnG/cDzucHxx/bK9zRGExPNy1R3pL2gcyR4jxBWbl+EvOqePmeF96gW3sEcynC424YjyPcOTBCJDI45LkwAdRBDzcEKtN49ra96Z+6sk3nexBK31nmjJUYjHpYYFfMUNCyGuJKEvGKaG8YCwxW/6YehB1aXfqJd3UOjtq1Pmb0YWFpwPGBn02U6HdTJ6nmUxfOg1XpUfnqGBMaa1kkgUHZpWcqYVeyhrFAjTyMye5ebhf6xFVl2LnvW15tqm8hQ4ZCrorJhmTTn4
  template:
    metadata:
      name: authentik-oauth-immich
      namespace: personal
