apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: storage-secret-store
  namespace: personal # This must be in the personal namespace
spec:
  provider:
    kubernetes:
      # This points to the storage namespace
      remoteNamespace: storage
      auth:
        serviceAccount:
          name: eso-kubernetes-backend
          namespace: security
