apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: storage-secret-store
  namespace: personal
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-10"
spec:
  provider:
    kubernetes:
      # This points to the storage namespace
      remoteNamespace: storage
      auth:
        serviceAccount:
          name: eso-kubernetes-backend
          namespace: security
