apiVersion: v1
kind: Secret
metadata:
  name: immich-admin-credentials
  namespace: personal
stringData:
  ADMIN_EMAIL: "admin@ruth.example.com"
  ADMIN_PASSWORD: "eqnVMTXOpb5nZrIxdmC8vQSam6N04ntq"
  ADMIN_NAME: "Platform Admin"
