apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/services/obsidian/base

components:
  - ../../../apps/services/obsidian/components/secrets
  - ../../../apps/services/obsidian/components/ingress
  - ../../../apps/services/obsidian/components/dns-fix
  - ../../../apps/services/obsidian/components/storage
  - ../../../apps/services/obsidian/components/auth-authentik
  # - ../../../apps/services/obsidian/components/maintenance
