---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-db-credentials
  namespace: personal
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    DB_DATABASE_NAME: AgCnBRmZGG96+V+GBKWU/e3BaElhylGEbS2lCPz84SVRUH8v5DZRYm147fsqdAKmgMoZOrPMX7MDN7UXiWqlznKizSyGxvcjoiWWWZXIgRyzAlrhOdx3hUlTdg06RR2SoCAAhNAM39pNj5yAnnFQ9xpLRpPltqehuw1X+04FUWHkCWvzJUvDVFX3IbjpLfvezU2nCa6+JoMsSDMSvyw4vLi3X3qdEtXNDMzC5BJEJEv9ZdObBELZ04MhljfNoC/Y2BXEei1yfkeeQiX0wXflg4O8o6wevJJVrlstp7IjGn9/3SjfVpZ2xDr7T3ODJa9ZOLReiAxr+4tIG3D4LOWh6HtB13Vpt0jWOT9tCAOKZCENKoD7/mPlLE4Mb/RDRPnsgGfLVqCryS4JVQ4f0Lq4jWQ4twdSwe8nNSpmlUY/UnUy4fRpl7Cux7wEzMoN9hj1a4s6SlykCAzs74suNF5ZKuRsDaxX2OOi4BzjPvPCX8XIzGDvynVXEHKrlJ4REfrwXxnuUmb4r6El5sQrJ9RMoUu1LqEAk75f3XaqKWl1FIDXDjIFTv8fUX49qDUw8vu1c1tTGFDMtLANeqslZz6N4w2db8InAyk3vQ/y3qX1ih6+Tm6oTIuOM1JibKoXFuJ6pjfS4feZ+hk09Jz2nnke4WSl/TK1y5R3AyFFHH6Gw9oryNMRYnoBwZp8Wur27jWXuKsCfOeaVC0=
    DB_PASSWORD: AgBJg37T/SIRNUOJesQfy/ghMYvPio9lOULbeMVvEHQpbnAAgHmTFHPUfvlU22t07rVle+yFpq9pKxMVg30glhbOgalZ46lcXSnsu9G38lGExgCehhqNLLLZ+Ie0QTYMMOd4uXqFcpVEG5Zr4XKUxKslxYrJ/xIRyja/jhQXYspF619QpmMUXgHBO14N6WevLsiM1i4rQU1LpmRkWvFGH4JqWOQYGQMpDn+rUgptOsIgqQ1mBJ0z7Fj9WIi8wB/E3zA5Wnqi1W2pE5xkUZbGGurZCo6Uph7Qsqet6EYdKd7BNJUOwvcCy3hF0PJXkIBtulIHMjaI1KgAI4GuPseSEihABKc8c17kohynpGzn0K1EMurgd0REewfrNvyW1Z3oM9cpLH53uULMTicuct6vQP/mdbEzfcKuV14SPhBe6PFGJezdO9Cs5LkewupIO9IHN+mcXmL+fbav5xtbPtR4j6lEBFIZ4PO+j/n8QFxWsFq6URtTyMVYEDD7rdMP/8Vkl//Ml6WjrtpDO2H5RG24ex531XDjlpw1EO1tvQHF9DqVqknUiX5vyBgXVtqVfDTiGB1MXRY/ZQnF9fn9K5iGZXsRqxf+wvexdTAbgw+/sXitKOzrHMJTmuYPaQ8NyoJzh/yszXEGbMGKs7+yM7+fv7iE+ITYNi+SwL911poqmGpW4aacID9cmzw/p0PHYHgtBoIUMRJwP02D2b5/2QHNg6mk4CGWQkCOvlTwSqfsu8FjQ0HYFw==
    DB_USERNAME: AgC+G02E2Srk6I1VBsXagaZGSBSobyYebWbjIy97iXzFqrD//OZ+cZM6jqricsxX77jwPgX7SoXVeJFVhr01eQZDMHFzWpjS8IN8bsLqx/1g0z9FAz7Odo3gN0PW9/4FTZ+7XCz6aX8puAoWd0bhYVGAyVJNl2KvEMylFDZvN04JYCigqPlf7g8+0kX9STceEi4wbgVTfVRcZOXbqGD8XTXSxr24tUo5E1SHFtoREf6mtXqphehHVm1PoWr8cWY4vjvj5GomblnwCmuywDP8WfK6tpIbsZyIbndgxusX83TnF3/oJCU2c3U8DJ2Wp05Tds6fmC4MRKnBLYJws/3CJSytuxlKt43WYi39h/Hbcdgr5KSKSZJX+dHlDg2la6ikSW6ThR7t/v2SETp1yTrnkTwA1GfteHbyXHcRxzCidB+YvCbAIrmI3ecWrjD4spKC2tEnuFGYVvOHaGZItmOSfZQWUGcEqv8EjOHLEuIRsqBJsQxHm+uZAhHSHmsP43dZ1nVINvvRrs1El9u6yaiFrrCAuJn1P/bc+kO5y/nnZLOoFqPkuBb1tD8qauq+y8wovDT1CL6/gRGcE904a9NL8oHN0b2GW7lkpDWAFhJ7Ce6fMJMyO1gEyeFKLy4vkOUaQnxcIccxc809gPDgkb9TLU+FKuY3RMH6kBFiKgc/jXUn99R+ZIsA7g2nuvRJwrrRWIuNR/Ku6mI=
  template:
    metadata:
      creationTimestamp: null
      name: immich-db-credentials
      namespace: personal
    type: Opaque
