apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pvc-library.yaml

patches:
  - path: patch-storage.yaml
    target:
      kind: PersistentVolumeClaim
      name: immich-library
