apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    releaseName: immich
    namespace: personal
    version: 0.10.3
    valuesInline:
      immich:
        persistence:
          library:
            existingClaim: immich-library

resources:
  - pvc-library.yaml
