apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
