apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: backup
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: velero
          ports:
            - name: metrics
              containerPort: 8085
