apiVersion: v1
kind: Service
metadata:
  name: node-exporter-prometheus-node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9101
      targetPort: 9101
