---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-repo-credentials
  namespace: backup
spec:
  encryptedData:
    repository-password: AgB6tp/VoA1269UEuAeaJZeC0Zpo6PudjPX/CRWIEjYKK4RhCqxs7OApc9PCjHWtHtnLMXn//AmWLg95JxFoB164hc0FINEMSugF4txr7RVUYcG69BgsbxdDykxVhYhW0PBiLVrWweAxf/WBF3u2IX+cy84WjyntmLB4fpyR4OyHTXpl4OeNOuWCldojEkXpoh4zS35eVIPgf6mXY9Y5xGI1rcD7STBaykJlXYfXVwIUcZCH9mInx1Sdrq/VtvF8X5WlnL0Cg/rky+kbkkS0xP6X5weKMZEMyKtIx7oFXAPTO2ajmTxwYJiLQBXyw/kIIoTkg1Fpk3e639MsImaW3fouBYooXsSZ2Lka/RVj+U74JfD8MgFoC1O80xmhGtlXYqWpsq9x1LAyLDBudwdrLb4J6HOEW8jYIod8/I0B1zyIs3SF6KPiha7gbDSW41txAQMGUc9C4hfEwR76H7ZJQgmJpKeZ+XdHylWgnIE68mona2qGK12qpwLSOKKLHTPvG6gTkknAj2PTkwK7LxULsm51hOqMGp0QyAQbTWZkd/DsrEs/PCU+sAOu6tCs6h1d9ZqzB5jbe6wqoe9bU7no4rJ42/3axGY9YYYOKwkYFMzhxDcmWYZImphyH/Vh0s5jk5vpZOBQtw9h+Fc1Mj/9w/vOlqKCWmljf9nGmFrq3VZH0opNYqyWfYG/R+DsZLZiLMENHePLDwdLN5yBNFxCx3OuYklPiLIUfxVlZXMKunVcRG9nCqM3tYcnnl3K7g==
  template:
    metadata:
      creationTimestamp: null
      name: velero-repo-credentials
      namespace: backup
