apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-14
spec:
  template:
    spec:
      containers:
        - name: postgres
          envFrom:
            - secretRef:
                name: postgres-credentials
