apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-config
  namespace: personal
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-secrets
    kind: ClusterSecretStore
  target:
    name: immich-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: immich-config-tpl
            items:
              - key: immich-config.yaml
                templateAs: Values
  data:
    - secretKey: IMMICH_OAUTH_CLIENT_ID
      remoteRef:
        key: authentik-oauth-immich
        property: IMMICH_OAUTH_CLIENT_ID
    - secretKey: IMMICH_OAUTH_CLIENT_SECRET
      remoteRef:
        key: authentik-oauth-immich
        property: IMMICH_OAUTH_CLIENT_SECRET
