apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - security-secret-store.yaml
  - external-config.yaml

configMapGenerator:
  - name: immich-config-tpl
    files:
      - immich-config.json
    options:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/sync-wave: "-3"
generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-volume.yaml
    target:
      kind: Deployment
      name: immich-server
