apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - external-config.yaml
patches:
  - path: patch-volume.yaml
    target:
      kind: Deployment
      name: immich-server
  - path: patch-volume.yaml
    target:
      kind: Deployment
      name: immich-microservices
