apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patch-limits.yaml
    target:
      kind: DaemonSet
      name: longhorn-manager
  - path: patch-limits.yaml
    target:
      kind: Deployment
      name: csi-provisioner
  - path: patch-limits.yaml
    target:
      kind: Deployment
      name: csi-attacher
  - path: patch-limits.yaml
    target:
      kind: Deployment
      name: csi-resizer
  - path: patch-limits.yaml
    target:
      kind: Deployment
      name: csi-snapshotter
  - path: patch-limits.yaml
    target:
      kind: Deployment
      name: longhorn-driver-deployer
