apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: DaemonSet
      labelSelector: "app.kubernetes.io/name=longhorn-manager"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  - target:
      kind: Deployment
      name: ".*csi-(provisioner|attacher|resizer|snapshotter).*"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 64Mi
  - target:
      kind: Deployment
      name: ".*longhorn-driver-deployer.*"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
