apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-manager
spec:
  template:
    spec:
      containers:
        - name: longhorn-manager
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-provisioner
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-attacher
spec:
  template:
    spec:
      containers:
        - name: csi-attacher
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-resizer
spec:
  template:
    spec:
      containers:
        - name: csi-resizer
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-snapshotter
spec:
  template:
    spec:
      containers:
        - name: csi-snapshotter
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
spec:
  template:
    spec:
      containers:
        - name: longhorn-driver-deployer
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
