apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
      name: metallb-controller
      namespace: networking
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metallb-controller
      spec:
        replicas: 1
