apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monthly-immich
  namespace: backup
spec:
  schedule: "30 20 1 * *" # 02:00 AM IST on the 2nd (20:30 UTC on the 1st) of every month
  template:
    includedNamespaces:
      - personal
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: immich
    storageLocation: aws
    defaultVolumesToFsBackup: true
    ttl: 720h0m0s # 30 days
