apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: StatefulSet
      name: redis-valkey
      namespace: storage
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: redis-valkey
      spec:
        template:
          spec:
            containers:
              - name: valkey
                resources:
                  limits:
                    cpu: 200m
                    memory: 256Mi
                  requests:
                    cpu: 50m
                    memory: 128Mi
