apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: personal

resources:
  - ingress-aritrosinha.yaml
  - ingress-strawslabs.yaml
  - cert-aritrosinha.yaml
  - cert-strawslabs.yaml