---
# defaults/main.yml - Default variables for the nas role

nas_server: "192.168.0.2"
nas_remote_path: "/WD4TB/shared/v1"
nas_mount_path: "/export/data"
nas_mount_options: "hard,noatime,actimeo=2"

nas_client_packages:
  - nfs-common

nas_server_packages:
  - nfs-kernel-server
  - samba
