apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cluster-secret-store.yaml
  - external-secret.yaml

patches:
  - path: patch-loki-read.yaml
    target:
      kind: StatefulSet
      name: loki-read
  - path: patch-loki-write.yaml
    target:
      kind: StatefulSet
      name: loki-write
  - path: patch-loki-backend.yaml
    target:
      kind: StatefulSet
      name: loki-backend
  - path: patch-loki-canary.yaml
    target:
      kind: DaemonSet
      name: loki-canary
