apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: aws
  namespace: backup
spec:
  provider: aws
  objectStorage:
    bucket: aritro-homelab-velero-backups
  config:
    region: ap-south-1
  credential:
    name: velero-aws-creds
    key: cloud
