apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-14
spec:
  serviceName: postgresql-14
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-14
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-14
    spec:
      containers:
        - name: postgres
          image: tensorchord/pgvecto-rs:pg14-v0.2.0
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: superadminpassword # In a real scenario, this should be a SealedSecret
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgresql
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 15Gi
        volumeMode: Filesystem
