adminPassword: admin

persistence:
  enabled: true

serviceMonitor:
  enabled: false

ingress:
  enabled: false

sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true
    label: grafana_dashboard
