apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: DaemonSet
      name: alloy
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: alloy
      spec:
        template:
          spec:
            nodeSelector:
              maintenance: "true"
