apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: obsidian

resources:
  - ../../../apps/services/obsidian/base

components:
  - ./components/secrets
  - ./components/ingress
  - ./components/dns-fix
  - ../../../apps/services/obsidian/components/storage
  - ./components/storage-nfs
  - ../../../apps/services/obsidian/components/auth-authentik
  # - ../../../apps/services/obsidian/components/maintenance
