apiVersion: batch/v1
kind: CronJob
metadata:
  name: immich-rclone-backup
spec:
  schedule: "0 0 1 * *" # 1st of every month
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rclone
              image: rclone/rclone:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Syncing Immich Library to AWS S3..."
                  rclone sync /data aws:hyperion-immich-file --transfers 4 --checkers 8 --verbose
              env:
                - name: RCLONE_CONFIG_AWS_TYPE
                  value: s3
                - name: RCLONE_CONFIG_AWS_PROVIDER
                  value: AWS
                - name: RCLONE_CONFIG_AWS_REGION
                  value: ap-southeast-1
                - name: RCLONE_CONFIG_AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: immich-aws-creds
                      key: AWS_ACCESS_KEY_ID
                - name: RCLONE_CONFIG_AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: immich-aws-creds
                      key: AWS_SECRET_ACCESS_KEY

              volumeMounts:
                - name: library
                  mountPath: /data
                  subPath: library
          volumes:
            - name: library
              persistentVolumeClaim:
                claimName: immich-library
          restartPolicy: OnFailure

