- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: blueprint-obsidian
    configMap:
      name: authentik-obsidian-blueprint
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: blueprint-obsidian
    mountPath: "/blueprints/mounted/obsidian-proxy"
