- op: add
  path: /spec/tls/-
  value:
    hosts:
      - obsidian.ruth.aritrosinha.dpdns.org
    secretName: obsidian-tls
- op: add
  path: /spec/rules/-
  value:
    host: obsidian.ruth.aritrosinha.dpdns.org
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: authentik-server
              port:
                number: 80
