apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/infrastructure/couchdb/base

components:
  - ../../../apps/infrastructure/couchdb/components/secrets
  - ../../../apps/infrastructure/couchdb/components/ingress
  # - ../../../apps/infrastructure/couchdb/components/maintenance
